markdown: kramdown
highlighter: pygments
permalink: /post/:year/:month/:day/:title/
excerpt_separator: "\n\n\n"

gauges_id: 503c5af6613f5d0f19000027
google_analytics_id: UA-50755011-1
twitter_username: js0n0
facebook_username: js0n0

repository: https://github.com/jekyll/jekyll
help_url: https://github.com/jekyll/jekyll-help

collections:
  docs:
    output: true
