markdown: kramdown
highlighter: pygments
permalink: /post/:categories/:year/:title/
excerpt_separator: "\n\n\n"

gauges_id: 503c5af6613f5d0f19000027

twitter_username: js0n0
facebook_username: js0n0

repository: https://github.com/jekyll/jekyll
help_url: https://github.com/jekyll/jekyll-help
paginate: 10
paginate_path: '/blog/page:num/' 
gems:
  - jekyll-sitemap

googleAnaly:
  config: false
  id: UA-12345678-1

baiduTongji:
  config: true
  id: 35812f595e2a9532207151e3c2bb34af

collections:
  docs:
    output: true
